# Основные настройки сайта
title: Персональное резюме
baseurl: "" # Базовый URL, если сайт размещен в подкаталоге
url: "https://yourwebsite.com" # URL вашего сайта

# Персональная информация
name: Иван Иванов
title: Старший разработчик C#
email: ivan.ivanov@example.com
phone: "+7 900 123-45-67"
location: Москва, Россия
linkedin: https://www.linkedin.com/in/your-profile
github: https://github.com/your-username

# Секция "Обо мне"
about: |
  Опытный разработчик C# с более чем 8-летним стажем в разработке корпоративных приложений.
  Специализируюсь на создании высоконагруженных бэкенд-систем с использованием .NET Core и ASP.NET.
  Обладаю глубокими знаниями LINQ, Lambda-выражений и асинхронного программирования.
  
  Стремлюсь к созданию чистого, поддерживаемого кода и постоянно изучаю новые технологии и методологии
  разработки. Имею опыт работы с микросервисной архитектурой и командной разработкой в Agile-окружении.

# Настройки сборки
markdown: kramdown
sass:
  style: compressed